#!/bin/bash

echo "📸 Screenshot Capture Helper for App Store Connect"
echo ""
echo "This script will help you capture the required screenshots."
echo ""
echo "REQUIRED SCREENSHOTS:"
echo "1. 6.5-inch iPhone (1242 x 2688 pixels)"
echo "2. 13-inch iPad (2048 x 2732 pixels)"
echo ""
echo "STEPS:"
echo "1. Open Xcode"
echo "2. Open your project: CalCalculatorAiPlaygournd.xcodeproj"
echo "3. Select device from dropdown:"
echo "   - iPhone 11 Pro Max (for 6.5-inch)"
echo "   - iPad Pro (12.9-inch) (for 13-inch)"
echo "4. Run the app (Cmd+R)"
echo "5. Navigate to the screen you want to capture"
echo "6. Take screenshot:"
echo "   - Cmd+S (saves to Desktop)"
echo "   - Or: Device → Screenshot"
echo ""
echo "RECOMMENDED SCREENS:"
echo "✓ Home screen with today's progress"
echo "✓ Food scanning/analysis screen"
echo "✓ Nutrition tracking dashboard"
echo "✓ Diet plan view"
echo "✓ Progress charts"
echo ""
echo "Screenshots will be saved to: ~/Desktop"
echo ""
echo "After capturing, rename them clearly:"
echo "  - iPhone-Home.png"
echo "  - iPhone-Scan.png"
echo "  - iPad-Home.png"
echo "  - iPad-Dashboard.png"
echo ""
